// Sample data
const clothingItems = [
    { name: 'T-shirt', image: '/images/tshirt.jpg', price: 599, description: 'Comfortable cotton T-shirt.', brand: 'H&M' },
    { name: 'Jeans', image: '/images/jeans.jpg', price: 999, description: 'Stylish denim jeans.', brand: 'Levi\'s' },
    { name: 'Jacket', image: '/images/jacket.jpg', price: 1799, description: 'Warm and stylish jacket.', brand: 'Zara' },
    { name: 'Sweater', image: '/images/sweater.jpg', price: 1299, description: 'Cozy knit sweater.', brand: 'Gap' },
    { name: 'Hat', image: '/images/hat.jpg', price: 499, description: 'Trendy hat.', brand: 'Forever 21' },
    { name: 'Shorts', image: '/images/shorts.webp', price: 699, description: 'Comfortable summer shorts.', brand: 'Jack & Jones' },
    { name: 'Skirt', image: '/images/skirt.jpeg', price: 799, description: 'Fashionable skirt.', brand: 'Mango' },
    { name: 'Sunglasses', image: '/images/sunglasses.webp', price: 1299, description: 'Stylish sunglasses.', brand: 'Ray-Ban' },
    { name: 'Scarf', image: '/images/scarf.avif', price: 699, description: 'Warm and elegant scarf.', brand: 'Marks & Spencer' },
    { name: 'Shoes', image: '/images/shoes.jpg', price: 1499, description: 'Comfortable and stylish shoes.', brand: 'Nike' },
    { name: 'Blouse', image: '/images/blouse.jpg', price: 899, description: 'Elegant blouse.', brand: 'Bershka' },
    { name: 'Cardigan', image: '/images/cardigan.jpeg', price: 1199, description: 'Cozy cardigan.', brand: 'H&M' },
    { name: 'Leggings', image: '/images/leggings.avif', price: 799, description: 'Comfortable leggings.', brand: 'Puma' },
    { name: 'Dress', image: '/images/dress.jpg', price: 1599, description: 'Stylish dress.', brand: 'Promod' },
    { name: 'Polo Shirt', image: '/images/polo-shirt.webp', price: 899, description: 'Casual polo shirt.', brand: 'Tommy Hilfiger' },
    { name: 'Blazer', image: '/images/blazer.webp', price: 2199, description: 'Elegant blazer.', brand: 'Ralph Lauren' },
    { name: 'Raincoat', image: '/images/raincoat.jpg', price: 1499, description: 'Waterproof raincoat.', brand: 'Columbia' },
    { name: 'Sweatshirt', image: '/images/sweatshirt.avif', price: 1199, description: 'Comfortable sweatshirt.', brand: 'Adidas' },
    { name: 'Cargo Pants', image: '/images/cargo_pants.avif', price: 1299, description: 'Stylish cargo pants.', brand: 'Uniqlo' },
    { name: 'Kimono', image: '/images/kimono.webp', price: 1499, description: 'Elegant kimono.', brand: 'Urban Outfitters' },
    { name: 'Vest', image: '/images/vest.webp', price: 899, description: 'Fashionable vest.', brand: 'Abercrombie' },
    { name: 'Jumpsuit', image: '/images/jumpsuit.avif', price: 1799, description: 'Trendy jumpsuit.', brand: 'Forever 21' },
    { name: 'Overalls', image: '/images/overalls.webp', price: 1599, description: 'Comfortable overalls.', brand: 'Levi\'s' },
    { name: 'Hoodie', image: '/images/hodddies.webp', price: 1399, description: 'Cozy hoodie.', brand: 'Nike' },
    { name: 'Pants', image: '/images/pants.avif', price: 999, description: 'Stylish pants.', brand: 'Jack & Jones' },
    { name: 'Belt', image: '/images/belts.avif', price: 499, description: 'Elegant belt.', brand: 'H&M' },
];

module.exports=clothingItems;